apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: consul
spec:
  containers:
  - name: readiness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 30; touch /tmp/healthy; sleep 600
